// AUTO-GENERATED. Run: npm run storybook:dashboard
// Generated: 2026-05-01T00:01:18.604Z

export const coverageBySubfolder: Array<{
  path: string;
  total: number;
  storied: number;
}> = [
  { path: 'ai', total: 18, storied: 1 },
  { path: 'auth', total: 3, storied: 0 },
  { path: 'calendar', total: 14, storied: 2 },
  { path: 'care', total: 7, storied: 0 },
  { path: 'central', total: 9, storied: 0 },
  { path: 'devices', total: 10, storied: 4 },
  { path: 'email', total: 9, storied: 1 },
  { path: 'errors', total: 1, storied: 0 },
  { path: 'examples', total: 1, storied: 0 },
  { path: 'finance', total: 90, storied: 7 },
  { path: 'handlers', total: 2, storied: 0 },
  { path: 'hr', total: 65, storied: 8 },
  { path: 'layout', total: 13, storied: 13 },
  { path: 'mobile', total: 11, storied: 0 },
  { path: 'modals', total: 9, storied: 0 },
  { path: 'production', total: 3, storied: 0 },
  { path: 'punch', total: 1, storied: 0 },
  { path: 'rbac', total: 3, storied: 0 },
  { path: 'sales', total: 18, storied: 8 },
  { path: 'shared', total: 33, storied: 30 },
  { path: 'signature', total: 2, storied: 0 },
  { path: 'stock', total: 16, storied: 7 },
  { path: 'storage', total: 35, storied: 0 },
  { path: 'support', total: 1, storied: 0 },
  { path: 'tasks', total: 47, storied: 0 },
  { path: 'ui', total: 72, storied: 52 },
];

export const deprecatedComponents: Array<{ file: string; count: number }> = [];

export const storiesWithoutPlay: string[] = [
  'src/components/ai/action-card.stories.tsx',
  'src/components/calendar/event-type-badge.stories.tsx',
  'src/components/calendar/recurrence-picker.stories.tsx',
  'src/components/devices/webhooks/auto-disabled-banner.stories.tsx',
  'src/components/devices/webhooks/delivery-status-badge.stories.tsx',
  'src/components/devices/webhooks/event-chip-selector.stories.tsx',
  'src/components/devices/webhooks/webhook-card.stories.tsx',
  'src/components/email/email-empty-state.stories.tsx',
  'src/components/finance/bulk-pay-drawer.stories.tsx',
  'src/components/finance/customer-score-badge.stories.tsx',
  'src/components/finance/duplicate-warning-banner.stories.tsx',
  'src/components/finance/escalation-timeline.stories.tsx',
  'src/components/finance/filter-presets.stories.tsx',
  'src/components/finance/installment-preview.stories.tsx',
  'src/components/finance/message-preview.stories.tsx',
  'src/components/hr/esocial-environment-badge.stories.tsx',
  'src/components/hr/esocial-status-chip.stories.tsx',
  'src/components/hr/kiosk/PinFallbackStage.stories.tsx',
  'src/components/hr/kiosk/ResultStage.stories.tsx',
  'src/components/hr/kudos-card.stories.tsx',
  'src/components/hr/medical-exam-timeline.stories.tsx',
  'src/components/hr/nps-score-card.stories.tsx',
  'src/components/hr/okr-progress-bar.stories.tsx',
  'src/components/layout/cart-indicator.stories.tsx',
  'src/components/layout/header.stories.tsx',
  'src/components/layout/navbar.stories.tsx',
  'src/components/layout/navigation-menu.stories.tsx',
  'src/components/layout/page-action-bar.stories.tsx',
  'src/components/layout/page-breadcrumb.stories.tsx',
  'src/components/layout/page-dashboard-sections.stories.tsx',
  'src/components/layout/page-hero-banner.stories.tsx',
  'src/components/layout/page-layout.stories.tsx',
  'src/components/layout/search-bar.stories.tsx',
  'src/components/layout/tenant-switcher.stories.tsx',
  'src/components/layout/tools-panel.stories.tsx',
  'src/components/layout/user-dropdown.stories.tsx',
  'src/components/sales/cart-sheet.stories.tsx',
  'src/components/sales/customer-credit-badge.stories.tsx',
  'src/components/sales/dashboard/sales-kpi-cards.stories.tsx',
  'src/components/sales/payment-overlay.stories.tsx',
  'src/components/sales/product-grid.stories.tsx',
  'src/components/sales/session-close-modal.stories.tsx',
  'src/components/sales/session-open-modal.stories.tsx',
  'src/components/sales/success-screen.stories.tsx',
  'src/components/shared/cards/entity-cards.stories.tsx',
  'src/components/shared/color-pattern-swatch.stories.tsx',
  'src/components/shared/confirm-dialog.stories.tsx',
  'src/components/shared/context-menu/entity-context-menu.stories.tsx',
  'src/components/shared/copy-button.stories.tsx',
  'src/components/shared/employee-selector.stories.tsx',
  'src/components/shared/empty-state.stories.tsx',
  'src/components/shared/error-boundary.stories.tsx',
  'src/components/shared/forms/attribute-manager.stories.tsx',
  'src/components/shared/forms/collapsible-section.stories.tsx',
  'src/components/shared/forms/dynamic-form-field.stories.tsx',
  'src/components/shared/forms/entity-form.stories.tsx',
  'src/components/shared/grid/entity-grid.stories.tsx',
  'src/components/shared/info-field.stories.tsx',
  'src/components/shared/loading-skeletons.stories.tsx',
  'src/components/shared/loading-spinner.stories.tsx',
  'src/components/shared/metadata-section.stories.tsx',
  'src/components/shared/modals/dialog-header.stories.tsx',
  'src/components/shared/modals/help-modal.stories.tsx',
  'src/components/shared/modals/import-modal.stories.tsx',
  'src/components/shared/modals/multi-view-modal.stories.tsx',
  'src/components/shared/modals/quick-create-modal.stories.tsx',
  'src/components/shared/photo-upload-dialog.stories.tsx',
  'src/components/shared/search/search-section.stories.tsx',
  'src/components/shared/stats-card.stories.tsx',
  'src/components/shared/stats/stats-section.stories.tsx',
  'src/components/shared/timeline/timeline.stories.tsx',
  'src/components/shared/user-avatar.stories.tsx',
  'src/components/shared/viewers/entity-viewer.stories.tsx',
  'src/components/stock/attachments/attachment-list.stories.tsx',
  'src/components/stock/batch-operation-progress-dialog.stories.tsx',
  'src/components/stock/page-header.stories.tsx',
  'src/components/stock/products/care-instructions-section.stories.tsx',
  'src/components/stock/variants/pattern-display.stories.tsx',
  'src/components/stock/variants/variant-list.stories.tsx',
  'src/components/stock/variants/variant-manager.stories.tsx',
  'src/components/ui/accordion.stories.tsx',
  'src/components/ui/alert-dialog.stories.tsx',
  'src/components/ui/alert.stories.tsx',
  'src/components/ui/avatar.stories.tsx',
  'src/components/ui/breadcrumb.stories.tsx',
  'src/components/ui/calendar.stories.tsx',
  'src/components/ui/card.stories.tsx',
  'src/components/ui/category-combobox.stories.tsx',
  'src/components/ui/checkbox.stories.tsx',
  'src/components/ui/color-picker.stories.tsx',
  'src/components/ui/combobox.stories.tsx',
  'src/components/ui/command.stories.tsx',
  'src/components/ui/country-select.stories.tsx',
  'src/components/ui/currency-input.stories.tsx',
  'src/components/ui/date-picker.stories.tsx',
  'src/components/ui/date-time-picker.stories.tsx',
  'src/components/ui/dialog.stories.tsx',
  'src/components/ui/drawer.stories.tsx',
  'src/components/ui/dropdown-menu.stories.tsx',
  'src/components/ui/emoji-picker.stories.tsx',
  'src/components/ui/filter-dropdown.stories.tsx',
  'src/components/ui/hover-card.stories.tsx',
  'src/components/ui/input-form.stories.tsx',
  'src/components/ui/input-otp.stories.tsx',
  'src/components/ui/kbd.stories.tsx',
  'src/components/ui/navigation-wizard-dialog.stories.tsx',
  'src/components/ui/numpad.stories.tsx',
  'src/components/ui/pagination.stories.tsx',
  'src/components/ui/password-input.stories.tsx',
  'src/components/ui/password-strength-checklist.stories.tsx',
  'src/components/ui/popover.stories.tsx',
  'src/components/ui/progress.stories.tsx',
  'src/components/ui/radio-group.stories.tsx',
  'src/components/ui/rotating-code-display.stories.tsx',
  'src/components/ui/scroll-area.stories.tsx',
  'src/components/ui/select.stories.tsx',
  'src/components/ui/separator.stories.tsx',
  'src/components/ui/sheet.stories.tsx',
  'src/components/ui/skeleton.stories.tsx',
  'src/components/ui/slider.stories.tsx',
  'src/components/ui/sonner.stories.tsx',
  'src/components/ui/step-wizard-dialog.stories.tsx',
  'src/components/ui/switch.stories.tsx',
  'src/components/ui/tabs.stories.tsx',
  'src/components/ui/textarea.stories.tsx',
  'src/components/ui/time-picker.stories.tsx',
  'src/components/ui/toggle-group.stories.tsx',
  'src/components/ui/toggle.stories.tsx',
  'src/components/ui/tooltip.stories.tsx',
];

export const recentStories: Array<{ file: string; modifiedAt: string }> = [
  {
    file: 'src/components/ai/action-card.stories.tsx',
    modifiedAt: '2026-04-30 20:08:19 -0300',
  },
  {
    file: 'src/components/calendar/event-type-badge.stories.tsx',
    modifiedAt: '2026-04-30 20:08:19 -0300',
  },
  {
    file: 'src/components/calendar/recurrence-picker.stories.tsx',
    modifiedAt: '2026-04-30 20:08:19 -0300',
  },
  {
    file: 'src/components/devices/webhooks/auto-disabled-banner.stories.tsx',
    modifiedAt: '2026-04-30 20:08:19 -0300',
  },
  {
    file: 'src/components/devices/webhooks/delivery-status-badge.stories.tsx',
    modifiedAt: '2026-04-30 20:08:19 -0300',
  },
  {
    file: 'src/components/devices/webhooks/event-chip-selector.stories.tsx',
    modifiedAt: '2026-04-30 20:08:19 -0300',
  },
  {
    file: 'src/components/devices/webhooks/webhook-card.stories.tsx',
    modifiedAt: '2026-04-30 20:08:19 -0300',
  },
  {
    file: 'src/components/email/email-empty-state.stories.tsx',
    modifiedAt: '2026-04-30 20:08:19 -0300',
  },
  {
    file: 'src/components/finance/bulk-pay-drawer.stories.tsx',
    modifiedAt: '2026-04-30 20:08:19 -0300',
  },
  {
    file: 'src/components/finance/customer-score-badge.stories.tsx',
    modifiedAt: '2026-04-30 20:08:19 -0300',
  },
];
