export type {
  AdmissionInvite,
  AdmissionStatus,
  AdmissionDocument,
  AdmissionDocumentType,
  AdmissionDocumentStatus,
  DigitalSignature,
  DigitalSignatureType,
  CandidateData,
  CandidateDependant,
  CreateAdmissionData,
  UpdateAdmissionData,
  ContractType,
  WorkRegime,
  MaritalStatus,
  BankAccountType,
  DependantRelationship,
  PublicAdmissionInvite,
} from '@/types/hr';
